### ISSUE TITLE
Add image versioning

### ISSUE THREAD

**Issue by NikPaushkin** [puzl-ee/docker-images#11]
## Problem
We must have option of rollback if some issue happened after update of image.

## Solution
Segregate Docker images by unique version in image's tag.

## ToDo
- [x] Add version to global dependencies
- [x] Add semver version to `metadata.json` of each image
- [x] Combine both versions in image tag like `g%globals_version%-%image_version%`
- [x] Do not push image from `master` branch to registry if tag already exists

**Comment by sergeimonakhov** [comment]
https://github.com/puzl-ee/docker-images/pull/13
